name: Update sprite files
on:
  schedule:
  - cron: 0 0 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sprite:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/create-pr-action@v2
      with:
        EXECUTE_COMMANDS: |
          git clone --depth 1 https://github.com/IsraelHikingMap/Site.git
          cp -up Site/IsraelHiking.Web/src/content/sprite/sprite* Icons/publish
          rm -fr Site
        COMMIT_MESSAGE: 'chore: update sprite files'
        COMMIT_NAME: 'GitHub Actions'
        COMMIT_EMAIL: 'example@example.com'
        PR_BRANCH_NAME: 'chore-sprite-update-${PR_ID}'
        PR_TITLE: 'chore: update sprite files'
